config/routes.rb
Rails.application.routes.draw do

  resources :bells do
    resources :calls
  end
  
  root 'bells#index'
  

end

app/models/bell.rb
class Bell < ActiveRecord::Base
  has_many :calls
  
  def has_active_call?
    calls.size > 0 and calls.last.active
  end
  
  def active_call
    has_active_call? ? calls.last : nil
  end
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :bell
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bells_controller.rb
class BellsController < ApplicationController
  before_action :set_bell, only: [:show, :edit, :update, :destroy]

  # GET /bells
  # GET /bells.json
  def index
    @bells = Bell.all
  end

  # GET /bells/1
  # GET /bells/1.json
  def show
    @at_home = "active"
    @out = ""
  end

  # GET /bells/new
  def new
    @bell = Bell.new
  end

  # GET /bells/1/edit
  def edit
  end

  # POST /bells
  # POST /bells.json
  def create
    @bell = Bell.new(bell_params)

    respond_to do |format|
      if @bell.save
        format.html { redirect_to @bell, notice: 'Bell was successfully created.' }
        format.json { render :show, status: :created, location: @bell }
      else
        format.html { render :new }
        format.json { render json: @bell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bells/1
  # PATCH/PUT /bells/1.json
  def update
    respond_to do |format|
      if @bell.update(bell_params)
        format.html { redirect_to @bell, notice: 'Bell was successfully updated.' }
        format.json { render :show, status: :ok, location: @bell }
      else
        format.html { render :edit }
        format.json { render json: @bell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bells/1
  # DELETE /bells/1.json
  def destroy
    @bell.destroy
    respond_to do |format|
      format.html { redirect_to bells_url, notice: 'Bell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bell
      @bell = Bell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bell_params
      params.require(:bell).permit(:name, :address)
    end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: [:show, :edit, :update, :destroy]

  # GET /calls
  # GET /calls.json
  def index
    @calls = Call.all
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
    @diff = (Time.now - @call.created_at).round # in seconds
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
      @bell = Bell.find(@call.bell_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:bell_id, :action, :action_msg)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bells_helper.rb
module BellsHelper
end

app/helpers/buzzes_helper.rb
module BuzzesHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/bells/_form.html.haml
= form_for @bell do |f|
  - if @bell.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bell.errors.count, "error")} prohibited this bell from being saved:"
      %ul
        - @bell.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_area :address
  .actions
    = f.submit 'Save'

app/views/bells/edit.html.haml
%h1 Editing bell

= render 'form'

= link_to 'Show', @bell
\|
= link_to 'Back', bells_path

app/views/bells/index.html.haml
%div.page{data: {page: "bells"}}
	%div.navbar
		%div.navbar-inner
			%div.center Bells
			%div.right
				%a.link.icon-only.open-panel{href: "#"}
					%i.icon.icon-bars
	
	%div.page-content
		%h1 Listing bells

		%table
			%thead
				%tr
				%th Name
				%th
				%th
				%th

			%tbody
				- @bells.each do |bell|
					%tr
						%td= bell.name
						%td= link_to 'Show', bell
						%td= link_to 'Edit', edit_bell_path(bell)
						%td= link_to 'Destroy', bell, :method => :delete, :data => { :confirm => 'Are you sure?' }

		%br

		= link_to 'New Bell', new_bell_path

app/views/bells/new.html.haml
%h1 New bell

= render 'form'

= link_to 'Back', bells_path

app/views/bells/show.html.haml
%div.page{data: {page: "bell-show"}}
	%div.navbar
		%div.navbar-inner
			%div.center= @bell.name
			%div.right
				%a.link.icon-only.open-panel{href: "#"}
					%i.icon.icon-bars
	
	%div.page-content
		- if @bell.has_active_call?
			%div.content-block
				%p
					%a.button.button-big.button-fill.color-red.long-blink{href: bell_call_path(@bell, @bell.active_call)} Someone Is Ringing!

		%div.content-block-title Where Are You?
		%div.content-block
			%p.buttons-row
				%a.button#btn-at-home{href: "#", class: @at_home} I Am Home
				%a.button#btn-out{href: "#", class: @out} I Am Out

		%div.content-block-title Configure Messages
		%div.list-block
			%ul
				%li
					%a.item-link.item-content.close-panel{href: "#"}
						%div.item-inner
							%div.item-title Welcome Message
							%div.item-after
				%li
					%a.item-link.item-content.close-panel{href: "#"}
						%div.item-inner
							%div.item-title Coming Message
							%div.item-after
				%li
					%a.item-link.item-content.close-panel{href: "#"}
						%div.item-inner
							%div.item-title Come Up Message
							%div.item-after
				%li
					%a.item-link.item-content.close-panel{href: "#"}
						%div.item-inner
							%div.item-title No Answer Message
							%div.item-after

		%div.content-block-title More
		%div.list-block
			%ul
				%li
					%a.item-link.item-content.close-panel{href: "#"}
						%div.item-inner
							%div.item-title Buzz Log
							%div.item-after
				%li
					%a.item-link.item-content.close-panel{href: "#"}
						%div.item-inner
							%div.item-title Devices And Token
							%div.item-after
			 
			%p#notice= notice

app/views/calls/_form.html.haml
= form_for @call do |f|
  - if @call.errors.any?
    #error_explanation
      %h2= "#{pluralize(@call.errors.count, "error")} prohibited this call from being saved:"
      %ul
        - @call.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :bell_id
    = f.number_field :bell_id
  .field
    = f.label :action
    = f.number_field :action
  .field
    = f.label :action_msg
    = f.text_field :action_msg
  .actions
    = f.submit 'Save'

app/views/calls/edit.html.haml
%h1 Editing call

= render 'form'

= link_to 'Show', @call
\|
= link_to 'Back', calls_path

app/views/calls/index.html.haml
%h1 Listing calls

%table
  %thead
    %tr
      %th Bell
      %th Action
      %th Action msg
      %th
      %th
      %th

  %tbody
    - @calls.each do |call|
      %tr
        %td= call.bell_id
        %td= call.action
        %td= call.action_msg
        %td= link_to 'Show', call
        %td= link_to 'Edit', edit_call_path(call)
        %td= link_to 'Destroy', call, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Call', new_call_path

app/views/calls/new.html.haml
%h1 New call

= render 'form'

= link_to 'Back', calls_path

app/views/calls/show.html.haml
%div.page{data: {page: "call-show"}}
	%div.navbar
		%div.navbar-inner
			%div.left
				%a.back.link{href: "#"}
					%i.icon.icon-back
					%span Back
			%div.center= "Call In #{@bell.name}"
			%div.right
				%a.link.icon-only.open-panel{href: "#"}
					%i.icon.icon-bars
					
	%div.page-content
		%div.content-block
			%div.content-block-inner
				%div.time-counter
					= hidden_field_tag("time-diff", @diff)
					%span#minutes 00
					%span m :
					%span#seconds 00
					%span s
				%div.time-counter-label Passed Since Call
		
		%div.content-block-title Respond To The Call
		%div.list-block
			%ul
				%li
					%a.item-link.item-content.close-panel#action-come-up{href: "#"}
						%div.item-inner
							%div.item-title Come Up
							%div.item-after
				%li
					%a.item-link.item-content.close-panel#action-coming{href: "#"}
						%div.item-inner
							%div.item-title I Am Coming
							%div.item-after
				%li
					%a.item-link.item-content.close-panel#action-coming-in{href: "#"}
						%div.item-inner
							%div.item-title Coming In ... Minutes
							%div.item-after
				%li
					%a.item-link.item-content.close-panel#action-cant{href: "#"}
						%div.item-inner
							%div.item-title Can't Make It
							%div.item-after
				%li
					%a.item-link.item-content.close-panel#action-custom-msg{href: "#"}
						%div.item-inner
							%div.item-title Custom Message
							%div.item-after
			
			%div.content-block
				%a.button.button-big.color-red{href: "#"} Discard Call

app/views/layouts/_panel.html.haml
%div.panel-overlay
%div.panel.panel-left.panel-cover.layout-white
	%div.content-block.avatar-block
		= image_tag("avatar.jpg", class: "avatar-img")
		%div.avatar-name Guillaume Deflaux
	%div.content-block-title My Bells
	%div.list-block
		%ul
			- Bell.all.each do |bell|	
				%li
					%a.item-link.item-content.close-panel{href: bell_path(bell)}
						%div.item-inner
							%div.item-title= bell.name
							%div.item-after
								- if bell.has_active_call?
									%span.badge.color-red.short-blink
	%div.content-block
		%a.button{href: "#"} Register A New Bell
	%div.content-block-title Settings
	%div.content-block
		%p
			%a.button{href: "#"} Edit Profile
		%p
			%a.button{href: "#"} Logout

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui"}/
		%meta{name: "apple-mobile-web-app-capable", content: "yes"}/
		%meta{name: "apple-mobile-web-app-status-bar-style", content: "black"}/
		%title Smart Bell
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= csrf_meta_tags

	%body.theme-green.layout-dark
		= render "layouts/panel"
		%div.views
			%div.view.view-main
				%div.pages.navbar-fixed
					= yield

		= javascript_include_tag 'application', 'data-turbolinks-track' => true